services:
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    depends_on:
      - dict-api
      - pix-analyser
      - dados-gov
      - receita-federal
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro 
    ports:
      - '80:80'
      - '443:443'
    restart: always
    networks:
      - public_network

  db-postgres:
    image: postgres:latest
    container_name: db_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data    
      - ./sql-scripts:/docker-entrypoint-initdb.d:ro
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    networks: 
      - private_network

  wait-for-db:
    image: willwill/wait-for-it
    command: db-postgres:5432 -t 30
    depends_on:
      - db-postgres
    networks:
      - private_network

  dict-api:
    build: ./dict-api/DictApi
    container_name: dict_api
    depends_on:
      - wait-for-db
    environment:
      DB_HOST: db-postgres
      DB_USER: postgres
      DB_PASSWORD: 123456
      POSTGRES_DB: dict_api
    networks: 
      - private_network
      - public_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  pix-analyser:
    build: ./java-service/PixKeyAnalyser
    container_name: pix_analyser
    depends_on:
      - wait-for-db
    environment:
      DB_HOST: db-postgres
      DB_USER: postgres
      DB_PASSWORD: 123456
      POSTGRES_DB: pix_analyser
    networks: 
      - private_network
      - public_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  dados-gov:
    build: ./registro-nacional/DadosGov
    container_name: dados_gov
    depends_on:
      - wait-for-db
    environment:
      DB_HOST: db-postgres
      DB_USER: postgres
      DB_PASSWORD: 123456
      POSTGRES_DB: dados_gov
    networks: 
      - private_network
      - public_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  receita-federal:
    build: ./registro-nacional/ReceitaFederalCNPJ
    container_name: receita_federal_cnpj
    depends_on:
      - wait-for-db
    environment:
      DB_HOST: db-postgres
      DB_USER: postgres
      DB_PASSWORD: 123456
      POSTGRES_DB: receita_federal_cnpj
    networks: 
      - private_network
      - public_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  private_network:
    driver: bridge
  public_network:
    driver: bridge

volumes:
  pgdata:
